services:
  aba_db:
    image: postgres:15
    restart: unless-stopped
    container_name: aba_db
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Database username from .env file.
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Database password from .env file.
      POSTGRES_DB: ${POSTGRES_DB} # Database name from .env file.
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Expose PostgreSQL port, can be overridden in .env file.
    networks:
      - aba_nw

  aba_app:
    build: .
    image: nairsrijith/abawebapp:testing
    restart: unless-stopped
    container_name: aba_app
    ports:
      - "8082:8080" # Update the port mapping as needed. Do not change the port number on right side of the ":" (colon).
    volumes:
      - ./data:/myapp/app/data # You can either have a local directory for data persistence or use a named volume.
      - ./assets/logo.png:/myapp/app/static/images/logo.png
    env_file: .env
    environment:
      TZ: ${TZ:-America/Toronto}  # Set timezone - adjust to your organization's timezone
      ORG_NAME: ${ORG_NAME:-Buzzing Minds}
      ORG_ADDRESS: ${ORG_ADDRESS:-123 Main St, Toronto, ON M4E 2V9}
      ORG_PHONE: ${ORG_PHONE:-(123) 456-7890}
      ORG_EMAIL: ${ORG_EMAIL:-support@testorg.com}
      PAYMENT_EMAIL: ${PAYMENT_EMAIL:-payments@testorg.com}
      POSTGRES_HOST: aba_db # This should match the service name of the database container.
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} # Default PostgreSQL port is 5432, can be overridden in .env file.
      POSTGRES_USER: ${POSTGRES_USER} # Database username from .env file.
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Database password from .env file.
      POSTGRES_DB: ${POSTGRES_DB} # Database name from .env file.
    networks:
      - aba_nw
    depends_on:
      - aba_db

networks:
  aba_nw:
    driver: bridge
